# Generated by Django 4.2.3 on 2025-05-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
